apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: firstpod
  name: firstpod
spec:
  containers:
  - image: httpd
    name: firstpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
